### ISSUE TITLE
Legend - proportionnal symbols

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map.js#11]
- Stop using https://d3-legend.susielu.com/ which is no longer maintained (apparently). Go for something even simpler !
Adopt something more compact such as what has been done for NutsDorlingCartogram or on the right here:
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcNmBE7UgO2MJOPWfVqDZCa1KMXtzlu6AVfA&usqp=CAU
- Use rounded values.
- Adapt for all kind of symbols, not only circles

**Comment by JoeWDavies** [comment]
1) Should we not expose the d3.format function to the user? to allow them to format the legend values? If unspecified then it could default to the current implementation `.labelFormat(format("." + out.labelDecNb_ + "f")`.

2) Would it not be more intuitive to expose the legend configuration as a single method which accepts a single configuration object? See [gridviz](https://github.com/eurostat/gridviz#legend) for example.

**Comment by jgaffuri** [comment]
Yes, good ideas !

2. with something like:
legend = function(map, opts) {
  opt.parameter1 = opt.parameter1 || defaultValue1;
  ...
}
?

**Comment by JoeWDavies** [comment]
Yes, in gridviz I first define a default legend configuration and then allow the user to override its properties:

  viewer.legend = function (viewer, config) {
    for (let key in config) {
      viewer.legend_[key] = config[key];
    }
    //update legend if necessary
    if (viewer._gridLegend) {
      updateLegend()
    }
    return viewer;
  };

**Comment by jgaffuri** [comment]
Excellent !

**Comment by jgaffuri** [comment]
- I adopted you approach with 'config' everywhere, not only for the legends. It make possible to define a map with `map("ch", { scale:"01M", ... })` in addition to the `map("ch").scale("01M")`
- I took care of redesigning the legends for choropleth and categorical maps without https://d3-legend.susielu.com/ . It is far simpler now !
