### ISSUE TITLE
Eurobase REST API migration

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map.js#111]
See documentation on new API and changes there:
•	https://ec.europa.eu/eurostat/online-help/public/en/NAVIGATION_WDDSTranslator_usage_en/
•	https://ec.europa.eu/eurostat/online-help/public/en/NAVIGATION_WDDSTranslator_migration_en/

**Comment by JoeWDavies** [comment]
Note: precision and filterNonGeo are now deprecated.

Also: 'geo' and 'geolevel' filters cannot be used simultaneously
