### ISSUE TITLE
Remove all Strokes possible for Chloropleth Map?

### ISSUE THREAD

**Issue by schntim** [eurostat/eurostat-map.js#130]
Dear Eurostat Developer Team, 

I'm trying to style a chloropleth map s.t. it only shows the shapes of the respective NUTS-Level (e.g. countries only). 
To get rid of all the borders, I have set all the strokewidth settings that are applicable to 0, nevertheless there is still a set of borders visible as depicted in the screenshot below. 

Am I missing a stroke setting or is this an issue with the library? 

Thank you for your support!

Code (excerpt): 
`
map = eurostatmap.map("ch")
...
.worldStroke("#FFFFFF00")
.worldCoastStroke("#FFFFFF00")
.worldCoastStrokeWidth(0)
.worldStrokeWidth(0)
.coastalMarginWidth(0)
.graticuleStrokeWidth(0)
.frameStrokeWidth(0)
.nutsbnStrokeWidth(0)
.cntbnStrokeWidth(0)
.cntbnStroke({0:"#FFFFFF00", 1:"FFFFFF00", 2:"FFFFFF00", 3:"#FFFFFF00", oth:"#FFFFFF00", co:"#FFFFFF00"})
...
`

Screenshot: 
![eurostatmap (6)](https://github.com/eurostat/eurostat-map.js/assets/6017026/cbc6abe4-c3c0-4b45-9a10-d49a5d46dc05)

**Comment by joewdavies** [comment]
Hi,

Apologies, I have only just seen this.

For cntbnstrokewidth and nutsbnstrokewidth you must specify the widths for each NUTS level as an object:

![image](https://github.com/eurostat/eurostat-map.js/assets/25485293/396baed8-2bb0-4735-8dba-7d82ff461089)

See https://github.com/eurostat/eurostat-map.js/blob/master/docs/reference.md#styling

and 

https://observablehq.com/@joewdavies/eurostat-map-js
