### ISSUE TITLE
categorical map example not working

### ISSUE THREAD

**Issue by palmajoao** [eurostat/eurostat-map.js#131]
the categorical example is not working 
https://eurostat.github.io/eurostat-map.js/examples/categorical.html 

most likely becaus the source data @ https://github.com/eurostat/eurostat-map.js/blob/b221f40a1c8cce0d48fbc3df2bba7b7c2f73e816/examples/categorical.html#L20C31-L20C119 is returning a 404:
https://raw.githubusercontent.com/eurostat/eurostat-map.js/dev/examples/urb_rur_typo.csv

**Comment by joewdavies** [comment]
Thanks! I have fixed the URL
