### ISSUE TITLE
Statistical data API tabel in reference malformed

### ISSUE THREAD

**Issue by wldevries** [eurostat/eurostat-map.js#134]
https://github.com/eurostat/eurostat-map.js/blob/master/docs/reference.md#statistical-data

The method table in the Statistical data section does not format properly. I assume it's due to the missing titles for the _Default value_ and _Description_ column.

**Comment by joewdavies** [comment]
Thanks for picking up on this! Fixed https://github.com/eurostat/eurostat-map.js/commit/3bfbe168abd8ec3e6d52828c2af73cb373ddc491
