### ISSUE TITLE
diverging color ramps for choropleth maps

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map.js#16]
See: https://github.com/d3/d3-scale-chromatic/blob/master/README.md#diverging
The default value of central value should be 0. Other possibilities should be average, mean or user defined.

**Comment by joewdavies** [comment]
technically possible with `map.thresholds([])` and ,`map.colors([])`

As seen in IMAGE https://gisco-services.ec.europa.eu/image/
