### ISSUE TITLE
proportional symbols - make other symbols possible, not only circles

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map.js#18]
1. The "transform" attribute should be used to scale and move the group symbol instead of current circle radius.
2. Propose list of predefined symbols (circle, square, etc. see https://github.com/d3/d3-shape#symbols) and maybe user defined ones (as SVG paths)
3. Beside proportionnal symbols, vertical bars could also be proposed. In that case, the scaling of the symbol would occur only along the vertical dimension. Example: https://4.bp.blogspot.com/-IbwkPe0Cd7o/Tv74ukFKxbI/AAAAAAAAALw/hDwLkziybiw/s1600/barMap.png

**Comment by JoeWDavies** [comment]
regarding 1. :  please elaborate further. Why transform?
regarding 3. : Are vertical bars considered proportional symbols as well? or is a new map type required?
