### ISSUE TITLE
.psStrokeWidth not working

### ISSUE THREAD

**Issue by JoeWDavies** [eurostat/eurostat-map.js#26]
Proportional circle map stroke width setter only changes stroke width of legend circles:

  .psStrokeWidth(0.1)

**Comment by jgaffuri** [comment]
There was a bug ideed, due to the fact the the "transition" does not apply to stroke-width and do not change it.
It is now corrected in the new version 2.0.3.
Note however this other issue, which relates to stroke-width as well: https://github.com/eurostat/eurostat-map.js/issues/27

**Comment by JoeWDavies** [comment]
Thanks Julien, in that case I will close the issue.
