### ISSUE TITLE
Discrepancies in styling between Firefox and Chrome

### ISSUE THREAD

**Issue by joewdavies** [eurostat/eurostat-map.js#29]
Legend height and title fontsize are not applied correctly on firefox 83.0
![Screenshot from 2020-12-01 14-32-59](https://user-images.githubusercontent.com/25485293/100747323-2f0def80-33e2-11eb-96f2-d5e96e43a10b.png)

**Comment by JoeWDavies** [comment]
these appear to be due to the fact that chrome recognizes 12 as a font size when using .style("font-size",12), but it should in fact be .style("font-size","12px")
