### ISSUE TITLE
Implement space as default thousands separator

### ISSUE THREAD

**Issue by joewdavies** [eurostat/eurostat-map.js#67]
The publications team for the DRYB used a space as a thousands separator. maybe we should implement this as the default?

**Comment by JoeWDavies** [comment]
could be achieved by setting the following d3 locale:

        d3.formatDefaultLocale({  
            "decimal": ",",
            "thousands": " ",
            "grouping": [3],
            "currency": ["", "€"]
        })

then using d3.format(",.2r") to format the strings
