### ISSUE TITLE
how to visualize map?

### ISSUE THREAD

**Issue by tetrabrick** [eurostat/eurostat-map.js#85]
Please I have uploaded your master demo, but I am unable to visualize the map.
please check at:
http://orca-yachts.com/web/webapp/index.html 

help is welcome

**Comment by JoeWDavies** [comment]
I believe you are mistaken. This library is for visualizing statistical data of NUTS regions

**Comment by jgaffuri** [comment]
This is a ticket for https://github.com/eurostat/searoute
You posted your message at the wrong place...
